// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxPn0iaeRo0Z0mwmtbV11lrFopUHFr8tc',
    appId: '1:675230502476:web:7765df88095490e8a1aee9',
    messagingSenderId: '675230502476',
    projectId: 'artin-s-web',
    authDomain: 'artin-s-web.firebaseapp.com',
    storageBucket: 'artin-s-web.appspot.com',
    measurementId: 'G-WWPEFQ4237',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBds9ZgjUJNGhNF000lLp5c9NSReEJsyQk',
    appId: '1:675230502476:android:bf573c116e70ab76a1aee9',
    messagingSenderId: '675230502476',
    projectId: 'artin-s-web',
    storageBucket: 'artin-s-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9uAyPyIVUmXwlyrMZGwjqVpatC1oysGE',
    appId: '1:675230502476:ios:4ba7c1adc8d968bfa1aee9',
    messagingSenderId: '675230502476',
    projectId: 'artin-s-web',
    storageBucket: 'artin-s-web.appspot.com',
    iosBundleId: 'com.example.artinweb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9uAyPyIVUmXwlyrMZGwjqVpatC1oysGE',
    appId: '1:675230502476:ios:4e8090725c88bef3a1aee9',
    messagingSenderId: '675230502476',
    projectId: 'artin-s-web',
    storageBucket: 'artin-s-web.appspot.com',
    iosBundleId: 'com.example.artinweb.RunnerTests',
  );
}
